CC = g++
SOURCE = src\Randomizer.cpp src\main.cpp
OBJ = Randomizer.o main.o
EXE = bin\ps2rand.exe
CXXFLAGS = -std=gnu++11 -pipe -mthreads -D__GNUWIN32__ -D__WXMSW__ -DWXUSINGDLL -DwxUSE_UNICODE -Wall -g -IC:\wxWidgets-3.0.4\include -IC:\wxWidgets-3.0.4\lib\gcc_dll\mswu
LIBS = -LC:\wxWidgets-3.0.4\lib\gcc_dll  -mthreads  -lwxmsw30u -mwindows

all: $(OBJ)
	$(CC) -o $(EXE) $(OBJ) $(LIBS)

%.o: src/%.cpp 
	$(CC) -c $(SOURCE) $(CXXFLAGS) 

clean:
	del $(OBJ) $(EXE)