#ifndef POKECUP_HPP
#define POKECUP_HPP

#define POKE_CUP_RENTALS 0x170BB24
#define POKE_CUP_COUNT 246

#define POKE_CUP_MATCH1 0
#define POKE_CUP_MATCH2 0
#define POKE_CUP_MATCH3 0
#define POKE_CUP_MATCH4 0
#define POKE_CUP_MATCH5 0
#define POKE_CUP_MATCH6 0

#define POKE_CUP_2_MATCH1 0
#define POKE_CUP_2_MATCH2 0
#define POKE_CUP_2_MATCH3 0
#define POKE_CUP_2_MATCH4 0
#define POKE_CUP_2_MATCH5 0
#define POKE_CUP_2_MATCH6 0

#endif