#ifndef POKECUP_HPP
#define POKECUP_HPP

#define POKE_CUP_RENTALS 0x170BB24
#define POKE_CUP_COUNT 246

#define POKECUP_POKEBALL_BATTLE1 0
#define POKECUP_POKEBALL_BATTLE2 0
#define POKECUP_POKEBALL_BATTLE3 0
#define POKECUP_POKEBALL_BATTLE4 0
#define POKECUP_POKEBALL_BATTLE5 0
#define POKECUP_POKEBALL_BATTLE6 0
#define POKECUP_POKEBALL_BATTLES 0
#define POKECUP_POKEBALL_BATTLEF 0

#define POKECUP_GREATBALL_BATTLE1 0
#define POKECUP_GREATBALL_BATTLE2 0
#define POKECUP_GREATBALL_BATTLE3 0
#define POKECUP_GREATBALL_BATTLE4 0
#define POKECUP_GREATBALL_BATTLE5 0
#define POKECUP_GREATBALL_BATTLE6 0
#define POKECUP_GREATBALL_BATTLES 0
#define POKECUP_GREATBALL_BATTLEF 0

#define POKECUP_ULTRABALL_BATTLE1 0
#define POKECUP_ULTRABALL_BATTLE2 0
#define POKECUP_ULTRABALL_BATTLE3 0
#define POKECUP_ULTRABALL_BATTLE4 0
#define POKECUP_ULTRABALL_BATTLE5 0
#define POKECUP_ULTRABALL_BATTLE6 0
#define POKECUP_ULTRABALL_BATTLES 0
#define POKECUP_ULTRABALL_BATTLEF 0

#define POKECUP_MASTERBALL_BATTLE1 0
#define POKECUP_MASTERBALL_BATTLE2 0
#define POKECUP_MASTERBALL_BATTLE3 0
#define POKECUP_MASTERBALL_BATTLE4 0
#define POKECUP_MASTERBALL_BATTLE5 0
#define POKECUP_MASTERBALL_BATTLE6 0
#define POKECUP_MASTERBALL_BATTLES 0
#define POKECUP_MASTERBALL_BATTLEF 0

// SECOND ROUND

#define POKECUP_POKEBALL2_BATTLE1 0
#define POKECUP_POKEBALL2_BATTLE2 0
#define POKECUP_POKEBALL2_BATTLE3 0
#define POKECUP_POKEBALL2_BATTLE4 0
#define POKECUP_POKEBALL2_BATTLE5 0
#define POKECUP_POKEBALL2_BATTLE6 0
#define POKECUP_POKEBALL2_BATTLES 0
#define POKECUP_POKEBALL2_BATTLEF 0

#define POKECUP_GREATBALL2_BATTLE1 0
#define POKECUP_GREATBALL2_BATTLE2 0
#define POKECUP_GREATBALL2_BATTLE3 0
#define POKECUP_GREATBALL2_BATTLE4 0
#define POKECUP_GREATBALL2_BATTLE5 0
#define POKECUP_GREATBALL2_BATTLE6 0
#define POKECUP_GREATBALL2_BATTLES 0
#define POKECUP_GREATBALL2_BATTLEF 0

#define POKECUP_ULTRABALL2_BATTLE1 0
#define POKECUP_ULTRABALL2_BATTLE2 0
#define POKECUP_ULTRABALL2_BATTLE3 0
#define POKECUP_ULTRABALL2_BATTLE4 0
#define POKECUP_ULTRABALL2_BATTLE5 0
#define POKECUP_ULTRABALL2_BATTLE6 0
#define POKECUP_ULTRABALL2_BATTLES 0
#define POKECUP_ULTRABALL2_BATTLEF 0

#define POKECUP_MASTERBALL2_BATTLE1 0
#define POKECUP_MASTERBALL2_BATTLE2 0
#define POKECUP_MASTERBALL2_BATTLE3 0
#define POKECUP_MASTERBALL2_BATTLE4 0
#define POKECUP_MASTERBALL2_BATTLE5 0
#define POKECUP_MASTERBALL2_BATTLE6 0
#define POKECUP_MASTERBALL2_BATTLES 0
#define POKECUP_MASTERBALL2_BATTLEF 0

#endif