#ifndef PRIMECUP_HPP
#define PRIMECUP_HPP

#define PRIME_CUP_RENTALS 0x1708CB4
#define PRIME_CUP_COUNT 246

#define PRIME_CUP_MATCH1 0
#define PRIME_CUP_MATCH2 0
#define PRIME_CUP_MATCH3 0
#define PRIME_CUP_MATCH4 0
#define PRIME_CUP_MATCH5 0
#define PRIME_CUP_MATCH6 0

#define PRIME_CUP_2_MATCH1 0
#define PRIME_CUP_2_MATCH2 0
#define PRIME_CUP_2_MATCH3 0
#define PRIME_CUP_2_MATCH4 0
#define PRIME_CUP_2_MATCH5 0
#define PRIME_CUP_2_MATCH6 0


#endif