#ifndef PRIMECUP_HPP
#define PRIMECUP_HPP

#define PRIME_CUP_RENTALS 0x1708CB4
#define PRIME_CUP_COUNT 246

#define PRIMECUP_BATTLE1 0
#define PRIMECUP_BATTLE2 0
#define PRIMECUP_BATTLE3 0
#define PRIMECUP_BATTLE4 0
#define PRIMECUP_BATTLE5 0
#define PRIMECUP_BATTLE6 0
#define PRIMECUP_BATTLES 0
#define PRIMECUP_BATTLEF 0

#define PRIMECUP2_BATTLE1 0
#define PRIMECUP2_BATTLE2 0
#define PRIMECUP2_BATTLE3 0
#define PRIMECUP2_BATTLE4 0
#define PRIMECUP2_BATTLE5 0
#define PRIMECUP2_BATTLE6 0
#define PRIMECUP2_BATTLES 0
#define PRIMECUP2_BATTLEF 0

#endif