#ifndef POKECUP_HPP
#define POKECUP_HPP

#define POKE_CUP_RENTALS 0x170BB24
#define POKE_CUP_COUNT 246

#define POKECUP_POKEBALL_BATTLE1 0x170DB4C  // Nelson
#define POKECUP_POKEBALL_BATTLE2 0x170DBE4  // Bruce
#define POKECUP_POKEBALL_BATTLE3 0x170DC7C  // Chester
#define POKECUP_POKEBALL_BATTLE4 0x170DD14  // Clifford
#define POKECUP_POKEBALL_BATTLE5 0x170DDAC  // Alissa
#define POKECUP_POKEBALL_BATTLE6 0x170DE44  // Jenson
#define POKECUP_POKEBALL_BATTLES 0x170DEDC  // Claude
#define POKECUP_POKEBALL_BATTLEF 0x170DF74  // Mason

#define POKECUP_GREATBALL_BATTLE1 0x170E01C // Carmen
#define POKECUP_GREATBALL_BATTLE2 0x170E0B4 // Wyatt
#define POKECUP_GREATBALL_BATTLE3 0x170E14C // Cliff
#define POKECUP_GREATBALL_BATTLE4 0x170E1E4 // Dillon
#define POKECUP_GREATBALL_BATTLE5 0x170E27C // Molly
#define POKECUP_GREATBALL_BATTLE6 0x170E314 // Chen
#define POKECUP_GREATBALL_BATTLES 0x170E3AC // Baxter
#define POKECUP_GREATBALL_BATTLEF 0x170E444 // Pedro

#define POKECUP_ULTRABALL_BATTLE1 0x170E4EC // Nelson
#define POKECUP_ULTRABALL_BATTLE2 0x170E584 // Bruce
#define POKECUP_ULTRABALL_BATTLE3 0x170E61C // Chester
#define POKECUP_ULTRABALL_BATTLE4 0x170E6B4 // Clifford
#define POKECUP_ULTRABALL_BATTLE5 0x170E74C // Alissa
#define POKECUP_ULTRABALL_BATTLE6 0x170E7E4 // Jenson
#define POKECUP_ULTRABALL_BATTLES 0x170E87C // Claude
#define POKECUP_ULTRABALL_BATTLEF 0x170E914 // Mason

#define POKECUP_MASTERBALL_BATTLE1 0x170E9BC // Carmen
#define POKECUP_MASTERBALL_BATTLE2 0x170EA54 // Wyatt
#define POKECUP_MASTERBALL_BATTLE3 0x170EAEC // Cliff
#define POKECUP_MASTERBALL_BATTLE4 0x170EB84 // Dillon
#define POKECUP_MASTERBALL_BATTLE5 0x170EC1C // Molly
#define POKECUP_MASTERBALL_BATTLE6 0x170ECB4 // Chen
#define POKECUP_MASTERBALL_BATTLES 0x170ED4C // Baxter
#define POKECUP_MASTERBALL_BATTLEF 0x170EDE4 // Pedro

// SECOND ROUND

#define POKECUP_POKEBALL2_BATTLE1 0
#define POKECUP_POKEBALL2_BATTLE2 0
#define POKECUP_POKEBALL2_BATTLE3 0
#define POKECUP_POKEBALL2_BATTLE4 0
#define POKECUP_POKEBALL2_BATTLE5 0
#define POKECUP_POKEBALL2_BATTLE6 0
#define POKECUP_POKEBALL2_BATTLES 0
#define POKECUP_POKEBALL2_BATTLEF 0

#define POKECUP_GREATBALL2_BATTLE1 0
#define POKECUP_GREATBALL2_BATTLE2 0
#define POKECUP_GREATBALL2_BATTLE3 0
#define POKECUP_GREATBALL2_BATTLE4 0
#define POKECUP_GREATBALL2_BATTLE5 0
#define POKECUP_GREATBALL2_BATTLE6 0
#define POKECUP_GREATBALL2_BATTLES 0
#define POKECUP_GREATBALL2_BATTLEF 0

#define POKECUP_ULTRABALL2_BATTLE1 0
#define POKECUP_ULTRABALL2_BATTLE2 0
#define POKECUP_ULTRABALL2_BATTLE3 0
#define POKECUP_ULTRABALL2_BATTLE4 0
#define POKECUP_ULTRABALL2_BATTLE5 0
#define POKECUP_ULTRABALL2_BATTLE6 0
#define POKECUP_ULTRABALL2_BATTLES 0
#define POKECUP_ULTRABALL2_BATTLEF 0

#define POKECUP_MASTERBALL2_BATTLE1 0
#define POKECUP_MASTERBALL2_BATTLE2 0
#define POKECUP_MASTERBALL2_BATTLE3 0
#define POKECUP_MASTERBALL2_BATTLE4 0
#define POKECUP_MASTERBALL2_BATTLE5 0
#define POKECUP_MASTERBALL2_BATTLE6 0
#define POKECUP_MASTERBALL2_BATTLES 0
#define POKECUP_MASTERBALL2_BATTLEF 0

#endif